Custom InfoCard background
meteorlxy/vuepress-theme-meteorlxy pull request #32
Opened 2019-03-25 10:35 UTC by W-Qing

2019-03-26 10:19 UTC, meteorlxy requested changes
What's more, if the header background and the infocard background do not use geo in the mean time, we should find a way to remove geopattern to avoid it be bundled in.

2019-03-26 10:19 UTC, meteorlxy commented on docs/.vuepress/config.js
> +      background: 'https://www.meteorlxy.cn/assets/img/avatar.jpg',
Empty line between different properties is preferred

2019-03-26 10:19 UTC, meteorlxy commented on lib/index.js
> -
This should not be included

2019-03-26 10:19 UTC, meteorlxy commented on docs/_posts/2019-02-26-theme-guide-zh.md
> +
the english docs should be updated, too

2019-03-26 14:27 UTC, W-Qing commented on lib/index.js
> -
sorry, my bad.

2019-03-29 06:17 UTC, W-Qing commented
> What's more, if the header background and the infocard background do not use geo in the mean time, we should find a way to remove geopattern to avoid it be bundled in.

About this, do you have any good ideas? I don't know if we can use `import()` to dynamically load `Geopattern`.And this method seems to need to configure `Syntax Dynamic Import Babel Plugin` in `chainWebpack`.

2019-03-29 11:48 UTC, meteorlxy commented
Another way is to use `define` (webpack alias) to point `geopattern` to an empty file.

2019-09-27 06:44 UTC, closed without merging