add searchbox on header nav bar
meteorlxy/vuepress-theme-meteorlxy pull request #57
Opened 2019-08-05 13:33 UTC by cumthyb

- 在顶部导航栏添加了vuepress维护的searchbox
- 在config.js 添加空值searchbox显示的参数

2019-08-05 13:38 UTC, meteorlxy requested changes

2019-08-05 13:38 UTC, meteorlxy commented on yarn.lock
> +  resolved "https://registry.npm.taobao.org/@vuepress/plugin-search/download/@vuepress/plugin-search-1.0.3.tgz#f8cd98380cc00db067fb243e4fd298c6b8b7179a"
不要把淘宝源也提交上来哈

2019-08-05 16:01 UTC, cumthyb commented on yarn.lock
> +  resolved "https://registry.npm.taobao.org/@vuepress/plugin-search/download/@vuepress/plugin-search-1.0.3.tgz#f8cd98380cc00db067fb243e4fd298c6b8b7179a"
ok，I will fix it

2019-08-06 01:52 UTC, cumthyb commented on yarn.lock
> +  resolved "https://registry.npm.taobao.org/@vuepress/plugin-search/download/@vuepress/plugin-search-1.0.3.tgz#f8cd98380cc00db067fb243e4fd298c6b8b7179a"
> 不要把淘宝源也提交上来哈

done

2019-10-12 02:27 UTC, closed without merging